<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace GPBMetadata\Dto\User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>dto.user.UserSearchRequest</code>
 */
class UserSearchRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 page = 1;</code>
     */
    protected $page = 0;
    /**
     * Generated from protobuf field <code>uint64 perPage = 2;</code>
     */
    protected $perPage = 0;
    /**
     * Generated from protobuf field <code>string id = 3;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string name = 4;</code>
     */
    protected $name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $page
     *     @type int|string $perPage
     *     @type string $id
     *     @type string $name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pb\User\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 page = 1;</code>
     * @return int|string
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * Generated from protobuf field <code>uint64 page = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkUint64($var);
        $this->page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 perPage = 2;</code>
     * @return int|string
     */
    public function getPerPage()
    {
        return $this->perPage;
    }

    /**
     * Generated from protobuf field <code>uint64 perPage = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPerPage($var)
    {
        GPBUtil::checkUint64($var);
        $this->perPage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string id = 3;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 4;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

}

