<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace GPBMetadata\Pb\User;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¡
proto/user.protodto.user"L
UserSearchRequest
page (
perPage (

id (	
name (	"6

UserEntity

id (	
name (	
gender (	"F
UserSearchResult
total (#
items (2.dto.user.UserEntityB-ÊGPBMetadata\\Dto\\UserâGPBMetadata\\Pb\\Userbproto3'
        , true);

        static::$is_initialized = true;
    }
}

